server:
  port: 8889
spring:
  application:
    name: eureka-server-provider
  cloud:
    #开启重试机制，它默认是关闭的
    loadbalancer:
      retry:
        enable: true
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    ##设置心跳的周期间隔(默认90s)[如果10s没响应默认服务宕机]
    lease-expiration-duration-in-seconds: 10
    #设置心跳时间间隔(默认30s)[心跳时间2s]
    lease-renewal-interval-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://172.16.80.194:8888/eureka/
    #开启健康检查（需要spring-boot-starter-actuator依赖）
    healthcheck:
      enable: true
logging:
  level:
    root: debug