@startuml
class Context{
S/GetInput()
S/GetOutput()
}
abstract AbstractExpression{
Interpret(Context)
}
AbstractExpression..>Context
NonterminalExpression-up-|>AbstractExpression
TerminalExpression-up-|>AbstractExpression
@enduml