@startuml
class TestPaper{
QuestionA(){sout("问题")sout("答案")+AnswerA()}
QuestionB()
AnswerA()
AnswerB()
}
class TestPaperA{
AnswerA()
AnswerB()
}
class TestPaperB{
AnswerA()
AnswerB()
}
TestPaperA--up|>TestPaper
TestPaperB--up|>TestPaper
Main..>TestPaper
@enduml