@startuml
abstract class Subject{
+Attach(Observer)
+Detach(Observer)
+Notify()//通知
}
note "保存所有Observer,\n\
提供接口增加和删除Observer" as N1
N1-right-.. Subject
ConcreteSubject-up--|>Subject


abstract Observer{
+Update()
}
Subject "1" o-> "*"Observer
ConcreteObserver-up--|>Observer
main..>Subject
note "调用notify" as N2
N2 -left-..main


@enduml