@startuml
abstract class Operation{
double getResult()
}
class OperationAdd
class OperationDiv
class OperationMul
class OperationSub
class OperationFactory{
 {static} Operation create()
 }
 class Main
 Main..>OperationFactory
OperationFactory ..> Operation
'OperationFactory ..> OperationAdd
'OperationFactory ..> OperationSub
'OperationFactory ..> OperationMul
'OperationFactory ..> OperationDiv
Operation<|--OperationAdd
Operation<|--OperationSub
Operation<|--OperationMul
Operation<|--OperationDiv
@enduml