spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tx_demo?useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2.xml