@startuml
abstract class Command{
ExcuteCommand()
}
class Barbecuer{
}
class Waiter{
}
Command->Barbecuer
BakeMuttonCommand--up|>Command
BakeMuttonCommand--up|>Command
Waiter"1"->"*"Command
Main..>Command
Main..>Waiter


@enduml